extends:
    - stylelint-config-standard
rules:
    declaration-block-no-duplicate-properties: true
    at-rule-no-unknown:
        - true
        - ignoreAtRules:
              - tailwind
              - apply
              - variants
              - responsive
              - screen
    function-no-unknown:
        - true
        - ignoreFunctions:
              - theme
